python src/wave_generator_27.06.py \
    --root data/exp_1 \
    --x0 0 \
    --x1 10 \
    --dx 0.01 \
    --dt 10 \
    --nt 200 \
    --icf src.icf.polynomial \
    --fdim 3 \
    --fmin -2 \
    --fmax 2 \
    --fn 5 \
    --c 1